include: package:effective_dart/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    sdk_version_async_exported_from_core: ignore
  exclude:
    - 'lib/**.g.dart'
    - 'lib/**.gr.dart'
    - 'lib/services/adapters/**'
    - 'lib/config.iconfig.dart'

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    type_annotate_public_apis: false