include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    sdk_version_async_exported_from_core: ignore
  exclude:
    - "lib/**.g.dart"
    - "lib/**.gr.dart"

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    type_annotate_public_apis: false
