name: school_life
description: An app to manage your school life.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  outline_material_icons: any
  form_bloc: ^0.8.0
  flutter_form_bloc: ^0.7.0
  flutter_bloc: ^3.2.0
  flutter_statusbarcolor: ^0.2.3
  device_info: ^0.4.1+4
  google_fonts: ^0.3.7
  get_it: ^4.0.0-beta3
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  assorted_layout_widgets: ^1.0.14
  auto_route: ^0.2.2
  table_calendar: ^2.2.2
  flutter_material_color_picker: ^1.0.5

dev_dependencies:
  hive_generator: ^0.7.0
  auto_route_generator: ^0.2.2
  build_runner: ^1.7.3
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
