name: school_life
description: An app to manage your school life.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  collection: ^1.15.0
  dart_date: ^1.1.0
  fast_color_picker: ^0.1.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  meta: ^1.1.8
  pedantic: ^1.9.0
  reactive_date_time_picker: ^0.1.1
  reactive_forms: ^10.4.1
  stacked: ^2.1.8
  stacked_services: ^0.8.6
  stacked_themes: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^1.1.0
  mockito: ^5.0.10
  stacked_generator: ^0.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: NavBarIcons
      fonts:
        - asset: assets/fonts/NavBarIcons.ttf
