name: school_life
description: An app to manage your school life.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter_form_bloc: ^0.14.0
  get_it: ^4.0.1
  auto_route: ^0.4.4
  table_calendar: ^2.2.3
  injectable: ^0.3.0
  flutter_statusbarcolor: ^0.2.3
  animations: ^1.0.0+5
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  hive_generator: ^0.7.0+2
  auto_route_generator: ^0.4.5
  mockito: ^4.1.1
  injectable_generator: ^0.3.4
  effective_dart: ^1.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: NavBarIcons
      fonts:
        - asset: assets/fonts/NavBarIcons.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/BoldItalic.ttf
          weight: 700
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Montserrat/Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Montserrat/Bold.ttf
          weight: 700
          style: normal
