name: school_life
description: An app to manage your school life.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  outline_material_icons: any
  hive: any
  hive_flutter: any
  flutter_form_bloc: ^0.12.0+1
  get_it: ^4.0.1
  auto_route: ^0.4.3
  table_calendar: ^2.2.3
  injectable: ^0.3.0
  flutter_statusbarcolor: ^0.2.3
  animations: ^1.0.0+5
  flutter_bloc: ^3.2.0
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  hive_generator: ^0.7.0+2
  auto_route_generator: ^0.4.0
  mockito: ^4.1.1
  injectable_generator: ^0.3.3
  effective_dart: ^1.2.1

dependency_overrides:
  dartx: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: NavBarIcons
      fonts:
        - asset: assets/fonts/NavBarIcons.ttf
    - family: Laca
      fonts:
        - asset: assets/fonts/Laca/BoldItalic.otf
          weight: 700
          style: italic
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd/Book.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/CircularStd/Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/CircularStd/Bold.ttf
          weight: 700
          style: normal
