name: school_life
description: An app to manage your school life.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  outline_material_icons: any
  form_bloc: ^0.10.4
  flutter_form_bloc: ^0.10.6
  device_info: ^0.4.2+1
  google_fonts: ^0.3.9
  get_it: ^4.0.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  auto_route: ^0.3.1
  table_calendar: ^2.2.3
  injectable: ^0.3.0
  flare_flutter: ^2.0.1
  flutter_statusbarcolor: ^0.2.3
  animations: ^1.0.0+5
  flutter_week_view: ^0.2.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  auto_route_generator: ^0.3.2
  build_runner: ^1.8.0
  mockito: ^4.1.1
  injectable_generator: ^0.3.2
  effective_dart: ^1.2.1

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/animations/
