name: school_life
description: An app to manage your school life.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  flutter_bloc: ^6.0.1
  flutter_form_bloc: ^0.19.0
  get_it: ^4.0.4
  auto_route: ^0.6.7
  table_calendar: ^2.2.3
  animations: ^1.1.1
  flutter_svg: ^0.18.0
  pedantic: ^1.9.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  hive_generator: ^0.7.1
  auto_route_generator: ^0.6.8
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: NavBarIcons
      fonts:
        - asset: assets/fonts/NavBarIcons.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/BoldItalic.ttf
          weight: 700
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Montserrat/Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Montserrat/Bold.ttf
          weight: 700
          style: normal

