name: school_life
description: An app to manage your school life.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  outline_material_icons: any
  form_bloc: ^0.10.0
  flutter_form_bloc: ^0.10.0
  flutter_bloc: ^3.2.0
  device_info: ^0.4.1+4
  google_fonts: ^0.3.7
  get_it: ^3.1.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  auto_route: ^0.2.2
  table_calendar: ^2.2.2
  injectable: ^0.2.1
  flare_flutter: ^2.0.1
  flutter_statusbarcolor: ^0.2.3
  animations: ^1.0.0+5

dev_dependencies:
  hive_generator: ^0.7.0
  auto_route_generator: ^0.2.2
  build_runner: ^1.7.3
  mockito: ^4.1.1
  injectable_generator:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.1

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/animations/
